DefaultChatColor: "&7"
DefaultNameColor: "&8"


UsePlayerVaults: true

Prefix:
    bold: false
    maxlength: 10
    defaultColor: <gradient:red:yellow> # only applies to those who have changed it
    namebold: false